name: Cleanup Temporary Files

on:
  schedule:
    # Run at 1 AM every day
    - cron: '0 1 * * *'
  workflow_dispatch:
    # Allow manual triggering

jobs:
  cleanup:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Clean temporary files
        run: node scripts/cleanup.js
      
      - name: Commit changes if any
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add temp/ tmp/ cache/ 
          git diff --quiet && git diff --staged --quiet || (git commit -m "🧹 Auto cleanup temporary files [skip ci]" && git push)
